const depName = {
  quetzaltenango: "Quetzaltenango",
  huehuetenango: "Huehuetenango",
  chimaltenango: "Chimaltenango",
  suchitepequez: "Suchitepéquez",
  sacatepequez: "Sacatepéquez",
  altaverapaz: "Alta Verapaz",
  bajaverapaz: "Baja Verapaz",
  totonicapan: "Totonicapán",
  retalhuleu: "Retalhuleu",
  chiquimula: "Chiquimula",
  guatemala: "Guatemala",
  santarosa: "Santa Rosa",
  escuintla: "Escuintla",
  sanmarcos: "San Marcos",
  elprogreso: "El Progreso",
  jutiapa: "Jutiapa",
  zacapa: "Zacapa",
  jalapa: "Jalapa",
  quiche: "Quiché",
  solola: "Sololá",
  izabal: "Izabal",
  peten: "Petén",

  // HONDURAS
  atlantida: "Atlántida",
  choluteca: "Choluteca",
  colon: "Colón",
  comayagua: "Comayagua",
  copan: "Copán",
  cortes: "Cortés",
  elparaiso: "El Paraíso",
  francis: "Francisco Morazán",
  gracias: "Gracias a Dios",
  intibuca: "Intibucá",
  islasbahia: "Islas de la Bahía",
  lapaz: "La Paz",
  lempira: "Lempira",
  ocotepeque: "Ocotepeque",
  olancho: "Olancho",
  santabarbara: "Santa Bárbara",
  valle: "Valle",
  yoro: "Yoro",
};

export default depName;
